server:
  port: 8082
  eureka:
    instance:
      prefer-ip-address: true
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  gateway:
    discovery:
      locator:
        enabled: true

spring:
  cloud:
    gateway:
      routes:
        - id: retry_test
          uri: http://localhost:8082/service-alpha/alpha
          predicates:
            - Host=localhost
          filters:
            - name: Retry
              args:
                retries: 3
                series: SERVER_ERROR
                statuses: BAD_GATEWAY
                methods: GET,POST
                backoff:
                  firstBackoff: 5000ms
                  maxBackoff: 5000ms
                  factor: 1
                  basedOnPreviousValue: false
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      filters:
#        - name: Retry
#          args:
#            retries: 3
#            statuses: BAD_GATEWAY
#            methods: GET,POST