server:
  port: 8080
  eureka:
    instance:
      prefer-ip-address: true
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

  gateway:
    discovery:
      locator:
        enabled: true

spring:
cloud:
  loadbalancer:
    enabled: true
    gateway:
      filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
            methods: GET,POST
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false